# Generated by Django 2.1.7 on 2019-03-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_pos_lat', models.FloatField()),
                ('start_pos_long', models.FloatField()),
                ('end_pos_lat', models.FloatField()),
                ('end_pos_long', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('cost', models.FloatField()),
                ('free_slots', models.IntegerField()),
                ('total_slots', models.IntegerField()),
                ('passengers', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Active', 'Active'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=50)),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ridesharing.AppUser')),
            ],
        ),
    ]
