# Generated by Django 2.1.7 on 2019-03-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0002_ride'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='no_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
