# Generated by Django 2.1.7 on 2019-03-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0003_auto_20190317_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
