# Generated by Django 2.1.7 on 2019-03-17 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0004_ride_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='phone',
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
