# Generated by Django 2.1.7 on 2019-03-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0005_auto_20190317_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('In_Progress', 'In_Progress'), ('Finished', 'Finished'), ('Canceled', 'Canceled')], max_length=50),
        ),
    ]
