# Generated by Django 2.1.7 on 2019-03-17 05:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0006_auto_20190317_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passengers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
