# Generated by Django 2.1.7 on 2019-03-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridesharing', '0007_auto_20190317_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='trip_from',
            field=models.CharField(default='Start', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='trip_to',
            field=models.CharField(default='Start', max_length=100),
            preserve_default=False,
        ),
    ]
